import { QueryProvider, RecoilProvider } from '@/_context'
import '@/_ui/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '무드메이트',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-full desktop:w-[360px] desktop:mx-auto">
        <RecoilProvider>
          <QueryProvider>{children}</QueryProvider>
        </RecoilProvider>
      </body>
    </html>
  )
}
